apiVersion: apps/v1
kind: Deployment

metadata:
  name: kuberag-api
  namespace: kuberag

spec:
  replicas: 1

  selector:
    matchLabels:
      app: kuberag-api

  template:
    metadata:
      labels:
        app: kuberag-api

    spec:
      containers:
      - name: kuberag-api
        image: docker.io/library/kuberag-api:v4
        imagePullPolicy: Never

        ports:
        - containerPort: 8000

        env:
        - name: CHROMA_HOST
          value: "chromadb"
        - name: CHROMA_PORT
          value: "8000"
        - name: OLLAMA_URL
          value: "http://ollama:11434/api/generate"
        - name: OLLAMA_MODEL
          value: "llama3.2:1b"
        - name: HEALTH_MODEL_PATH
          value: "models/cluster_health_model.pkl"

        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
