apiVersion: apps/v1
kind: Deployment

metadata:
  name: kuberag-api
  namespace: kuberag

spec:
  replicas: 1

  selector:
    matchLabels:
      app: kuberag-api

  template:
    metadata:
      labels:
        app: kuberag-api

    spec:
      containers:
      - name: kuberag-api
        image: ghcr.io/tee82-debug/kuberag-api:latest
        imagePullPolicy: Always

        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3

        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20
          timeoutSeconds: 3
          failureThreshold: 3

        env:
        - name: CHROMA_HOST
          value: "chromadb"
        - name: CHROMA_PORT
          value: "8000"
        - name: OLLAMA_URL
          value: "http://ollama:11434/api/generate"
        - name: OLLAMA_MODEL
          value: "llama3.2:1b"
        - name: HEALTH_MODEL_PATH
          value: "models/cluster_health_model.pkl"

        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
